# Configuration for readthedocs

# New parameters for Read The Docs v2
# See also https://docs.readthedocs.io/en/stable/config-file/index.html

version: 2

# Important: we need to disable all unneeded formats.
# Note that HTML and JSON are always built:
# https://docs.readthedocs.io/en/latest/yaml-config.html#formats
# Especially, the 'htmlzip' format takes a LOT of memory and causes
# the build to fail - see our issue #1472:
# https://github.com/aiidateam/aiida-core/issues/1472
formats: []

build:
  image: stable

python:
    version: 3.6
    install:
      - requirements: docs/requirements_for_rtd.txt
      - method: pip
        path: .
        extra_requirements: []
    system_packages: false

## The conda environment can be heavy on the build,
## and is not essential for the documentation environment
# conda:
#   environment: environment.yml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false
